version: '3'

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: sensors/server
        environment:
            APP_PORT: 3000
        ports:
            - 3000:3000
        container_name: sensors_server
